[package]
name = "physics_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
parry2d-f64 = "0.13.7"
piston_window = "0.131.0"
